import os

# Base path - forward slashes work on Windows Python
B = "signverse-system/frontend"

def w(rel, lines):
    path = os.path.join(B, *rel.split("/"))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(lines)
    print("[OK]", rel)

w("lib/utils.ts", '\n'.join([
    'import { type ClassValue, clsx } from "clsx"',
    'import { twMerge } from "tailwind-merge"',
    '',
    'export function cn(...inputs: ClassValue[]) { return twMerge(clsx(inputs)) }',
    '',
    'export function formatBytes(bytes: number, decimals = 2): string {',
    '  if (bytes === 0) return "0 Bytes"',
    '  const k = 1024, sizes = ["Bytes","KB","MB","GB","TB"]',
    '  const i = Math.floor(Math.log(bytes) / Math.log(k))',
    '  return parseFloat((bytes / Math.pow(k, i)).toFixed(decimals)) + " " + sizes[i]',
    '}',
    'export function formatFPS(fps: number): string { return fps.toFixed(1) }',
    'export function formatMilliseconds(ms: number): string {',
    '  return ms < 1000 ? ms + "ms" : (ms/1000).toFixed(2) + "s"',
    '}',
    'export function generateId(): string {',
    '  return Math.random().toString(36).substring(2) + Date.now().toString(36)',
    '}',
    'export function capitalize(str: string): string { return str.charAt(0).toUpperCase() + str.slice(1) }',
    'export function truncate(str: string, length: number): string {',
    '  return str.length <= length ? str : str.slice(0, length) + "..."',
    '}',
    'export function sleep(ms: number): Promise<void> { return new Promise(r => setTimeout(r, ms)) }',
    'export function generateGradient(from: string, to: string): string {',
    '  return "linear-gradient(135deg, " + from + " 0%, " + to + " 100%)"',
    '}',
]))

w("store/use-system-store.ts", '\n'.join([
    'import { create } from "zustand"',
    'import { devtools } from "zustand/middleware"',
    '',
    'interface SystemState {',
    '  isProcessing: boolean; fps: number; latency: number; memoryUsage: number',
    '  showPose: boolean; showBoundingBoxes: boolean; showDepth: boolean; showInteractions: boolean',
    '  darkMode: boolean; detectedPersons: number; confidence: number; frameCount: number',
    '  startPipeline: () => void; stopPipeline: () => void',
    '  setFps: (v: number) => void; setLatency: (v: number) => void; setMemoryUsage: (v: number) => void',
    '  setShowPose: (v: boolean) => void; setShowBoundingBoxes: (v: boolean) => void',
    '  setShowDepth: (v: boolean) => void; setShowInteractions: (v: boolean) => void',
    '  setDarkMode: (v: boolean) => void; setDetectedPersons: (v: number) => void',
    '  setConfidence: (v: number) => void; incrementFrameCount: () => void; reset: () => void',
    '}',
    '',
    'const init = {',
    '  isProcessing:false, fps:0, latency:0, memoryUsage:0,',
    '  showPose:true, showBoundingBoxes:true, showDepth:false, showInteractions:true,',
    '  darkMode:true, detectedPersons:0, confidence:0, frameCount:0,',
    '}',
    '',
    'export const useSystemStore = create<SystemState>()(devtools((set) => ({',
    '  ...init,',
    '  startPipeline: () => set({ isProcessing:true, frameCount:0 }, false, "start"),',
    '  stopPipeline:  () => set({ isProcessing:false, fps:0, latency:0 }, false, "stop"),',
    '  setFps:               (fps)              => set({ fps },              false, "setFps"),',
    '  setLatency:           (latency)          => set({ latency },          false, "setLatency"),',
    '  setMemoryUsage:       (memoryUsage)      => set({ memoryUsage },      false, "setMemory"),',
    '  setShowPose:          (showPose)         => set({ showPose },         false, "setPose"),',
    '  setShowBoundingBoxes: (showBoundingBoxes)=> set({ showBoundingBoxes },false, "setBBox"),',
    '  setShowDepth:         (showDepth)        => set({ showDepth },        false, "setDepth"),',
    '  setShowInteractions:  (showInteractions) => set({ showInteractions }, false, "setInter"),',
    '  setDarkMode:          (darkMode)         => set({ darkMode },         false, "setDark"),',
    '  setDetectedPersons:   (detectedPersons)  => set({ detectedPersons },  false, "setPersons"),',
    '  setConfidence:        (confidence)       => set({ confidence },       false, "setConf"),',
    '  incrementFrameCount: () => set(s => ({ frameCount: s.frameCount+1 }), false, "incFrame"),',
    '  reset: () => set(init, false, "reset"),',
    '}), { name: "signverse-system" }))',
]))

w("app/globals.css", '\n'.join([
    '@tailwind base;',
    '@tailwind components;',
    '@tailwind utilities;',
    '',
    '@layer base {',
    '  :root {',
    '    --background: 222.2 84% 4.9%; --foreground: 210 40% 98%;',
    '    --card: 222.2 84% 4.9%; --card-foreground: 210 40% 98%;',
    '    --popover: 222.2 84% 4.9%; --popover-foreground: 210 40% 98%;',
    '    --primary: 239 84% 67%; --primary-foreground: 222.2 47.4% 11.2%;',
    '    --secondary: 217.2 32.6% 17.5%; --secondary-foreground: 210 40% 98%;',
    '    --muted: 217.2 32.6% 17.5%; --muted-foreground: 215 20.2% 65.1%;',
    '    --accent: 217.2 32.6% 17.5%; --accent-foreground: 210 40% 98%;',
    '    --destructive: 0 62.8% 30.6%; --destructive-foreground: 210 40% 98%;',
    '    --border: 217.2 32.6% 17.5%; --input: 217.2 32.6% 17.5%;',
    '    --ring: 239 84% 67%; --radius: 0.5rem;',
    '  }',
    '}',
    '@layer base { * { @apply border-border; } body { @apply bg-background text-foreground; } }',
    '::-webkit-scrollbar { width: 6px; height: 6px; }',
    '::-webkit-scrollbar-track { background: #0f172a; }',
    '::-webkit-scrollbar-thumb { background: #334155; border-radius: 3px; }',
    '::-webkit-scrollbar-thumb:hover { background: #475569; }',
    '.glass { background: rgba(30,41,59,.6); backdrop-filter: blur(12px); border: 1px solid rgba(99,102,241,.15); }',
    '.glow-primary { box-shadow: 0 0 20px rgba(99,102,241,.3); }',
    '.glow-accent  { box-shadow: 0 0 20px rgba(34,197,94,.3); }',
    '.glow-alert   { box-shadow: 0 0 20px rgba(239,68,68,.3); }',
]))

w("app/layout.tsx", '\n'.join([
    'import "./globals.css"',
    'import type { Metadata } from "next"',
    'import { Inter } from "next/font/google"',
    'import { DashboardLayout } from "@/components/layout/dashboard-layout"',
    'const inter = Inter({ subsets: ["latin"] })',
    'export const metadata: Metadata = {',
    '  title: "SignVerse - AI Perception Control System",',
    '  description: "Real-time monitoring and control for AI perception systems",',
    '}',
    'export default function RootLayout({ children }: { children: React.ReactNode }) {',
    '  return (',
    '    <html lang="en" className="dark">',
    '      <body className={inter.className}><DashboardLayout>{children}</DashboardLayout></body>',
    '    </html>',
    '  )',
    '}',
]))

w("components/layout/dashboard-layout.tsx", '\n'.join([
    '"use client"',
    'import { useState } from "react"',
    'import { Sidebar } from "./sidebar"',
    'import { Header } from "./header"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'interface DashboardLayoutProps { children: React.ReactNode }',
    'export function DashboardLayout({ children }: DashboardLayoutProps) {',
    '  const [open, setOpen] = useState(false)',
    '  const { darkMode } = useSystemStore()',
    '  return (',
    '    <div className={`min-h-screen ${darkMode ? "dark" : ""}`}>',
    '      <Sidebar open={open} onClose={() => setOpen(false)} />',
    '      <div className="lg:pl-72">',
    '        <Header onMenuClick={() => setOpen(true)} />',
    '        <main className="py-8"><div className="px-4 sm:px-6 lg:px-8">{children}</div></main>',
    '      </div>',
    '    </div>',
    '  )',
    '}',
]))

w("components/layout/sidebar.tsx", '\n'.join([
    '"use client"',
    'import Link from "next/link"',
    'import { usePathname } from "next/navigation"',
    'import { LayoutDashboard,Video,Users,Activity,Database,Settings,Bot,Workflow } from "lucide-react"',
    'import { cn } from "@/lib/utils"',
    'interface SidebarProps { open: boolean; onClose: () => void }',
    'const NAV = [',
    '  {name:"Dashboard",    href:"/",            icon:LayoutDashboard},',
    '  {name:"Monitoring",   href:"/monitoring",  icon:Video},',
    '  {name:"Tracking",     href:"/tracking",    icon:Users},',
    '  {name:"Pose Analysis",href:"/pose",        icon:Activity},',
    '  {name:"Interactions", href:"/interactions",icon:Workflow},',
    '  {name:"Datasets",     href:"/datasets",    icon:Database},',
    '  {name:"Models",       href:"/models",      icon:Bot},',
    '  {name:"Settings",     href:"/settings",    icon:Settings},',
    ']',
    'export function Sidebar({ open, onClose }: SidebarProps) {',
    '  const pathname = usePathname()',
    '  return (',
    '    <>',
    '      {open && <div className="fixed inset-0 z-50 bg-black/80 lg:hidden" onClick={onClose} />}',
    '      <div className={cn("fixed inset-y-0 left-0 z-50 w-72 bg-slate-950 border-r border-slate-800 transform transition-transform duration-300 lg:translate-x-0 lg:static lg:z-auto", open?"translate-x-0":"-translate-x-full")}>',
    '        <div className="flex items-center h-16 px-6 border-b border-slate-800">',
    '          <div className="flex items-center space-x-3">',
    '            <div className="w-8 h-8 bg-signverse-primary rounded-lg flex items-center justify-center glow-primary">',
    '              <Activity className="h-5 w-5 text-white" />',
    '            </div>',
    '            <span className="text-xl font-semibold text-white tracking-tight">SignVerse</span>',
    '          </div>',
    '        </div>',
    '        <nav className="mt-8 px-4">',
    '          <div className="space-y-1">',
    '            {NAV.map(item => {',
    '              const active = pathname === item.href',
    '              return (',
    '                <Link key={item.name} href={item.href} onClick={onClose}',
    '                  className={cn("flex items-center px-4 py-3 rounded-lg text-sm font-medium transition-all",',
    '                    active ? "bg-signverse-primary/10 text-signverse-primary border border-signverse-primary/20 shadow-lg shadow-signverse-primary/10"',
    '                           : "text-slate-400 hover:text-white hover:bg-slate-800/70")}>',
    '                  <item.icon className={cn("h-5 w-5 mr-3 flex-shrink-0", active && "text-signverse-primary")} />',
    '                  {item.name}',
    '                </Link>',
    '              )',
    '            })}',
    '          </div>',
    '        </nav>',
    '        <div className="absolute bottom-4 left-4 right-4 p-4 bg-slate-900/80 rounded-xl border border-slate-800 glass">',
    '          <div className="flex items-center justify-between mb-1">',
    '            <span className="text-xs font-medium text-slate-400 uppercase tracking-wider">System Status</span>',
    '            <div className="w-2 h-2 bg-signverse-accent rounded-full animate-pulse" />',
    '          </div>',
    '          <p className="text-xs text-slate-500">All systems operational</p>',
    '        </div>',
    '      </div>',
    '    </>',
    '  )',
    '}',
]))

w("components/layout/header.tsx", '\n'.join([
    '"use client"',
    'import { Menu, Bell, Settings, User } from "lucide-react"',
    'import { Button } from "@/components/ui/button"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'import { cn } from "@/lib/utils"',
    'interface HeaderProps { onMenuClick: () => void }',
    'export function Header({ onMenuClick }: HeaderProps) {',
    '  const { isProcessing, fps } = useSystemStore()',
    '  return (',
    '    <header className="flex items-center justify-between h-16 px-6 border-b border-slate-800 bg-slate-900/50 backdrop-blur-sm sticky top-0 z-40">',
    '      <div className="flex items-center space-x-4">',
    '        <Button variant="ghost" size="icon" className="lg:hidden text-slate-400 hover:text-white" onClick={onMenuClick}>',
    '          <Menu className="h-5 w-5" />',
    '        </Button>',
    '        <div className="flex items-center space-x-6 text-sm">',
    '          <div className="flex items-center space-x-2">',
    '            <div className={cn("w-2 h-2 rounded-full transition-colors", isProcessing ? "bg-signverse-accent animate-pulse" : "bg-slate-600")} />',
    '            <span className="text-slate-300">{isProcessing ? "Processing" : "Idle"}</span>',
    '          </div>',
    '          {isProcessing && <div className="font-mono text-xs bg-slate-800 px-2 py-1 rounded-md text-slate-400">{fps.toFixed(1)} FPS</div>}',
    '        </div>',
    '      </div>',
    '      <div className="flex items-center space-x-2">',
    '        <Button variant="ghost" size="icon" className="text-slate-400 hover:text-white relative">',
    '          <Bell className="h-5 w-5" />',
    '          <span className="absolute top-2 right-2 w-1.5 h-1.5 bg-signverse-primary rounded-full" />',
    '        </Button>',
    '        <Button variant="ghost" size="icon" className="text-slate-400 hover:text-white"><Settings className="h-5 w-5" /></Button>',
    '        <div className="w-8 h-8 bg-gradient-to-br from-signverse-primary to-violet-700 rounded-full flex items-center justify-center ml-1 cursor-pointer hover:opacity-90">',
    '          <User className="h-4 w-4 text-white" />',
    '        </div>',
    '      </div>',
    '    </header>',
    '  )',
    '}',
]))

w("components/stats/stats-grid.tsx", '\n'.join([
    '"use client"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'import { Activity, Users, Zap, Clock } from "lucide-react"',
    'import { cn, formatFPS, formatMilliseconds, formatBytes } from "@/lib/utils"',
    'const STATS = [',
    '  {id:"fps",    title:"Frame Rate",        icon:Zap,      color:"text-signverse-primary",bg:"bg-signverse-primary/10",border:"border-signverse-primary/20"},',
    '  {id:"persons",title:"Detected Persons",  icon:Users,    color:"text-signverse-accent", bg:"bg-signverse-accent/10", border:"border-signverse-accent/20"},',
    '  {id:"latency",title:"Inference Latency", icon:Clock,    color:"text-amber-400",        bg:"bg-amber-400/10",        border:"border-amber-400/20"},',
    '  {id:"memory", title:"Memory Usage",      icon:Activity, color:"text-violet-400",       bg:"bg-violet-400/10",       border:"border-violet-400/20"},',
    ']',
    'export function StatsGrid() {',
    '  const { fps, detectedPersons, latency, memoryUsage, isProcessing } = useSystemStore()',
    '  const vals: Record<string,string> = {',
    '    fps:     isProcessing ? formatFPS(fps) + " FPS"           : "- FPS",',
    '    persons: isProcessing ? String(detectedPersons)           : "-",',
    '    latency: isProcessing ? formatMilliseconds(latency)       : "- ms",',
    '    memory:  isProcessing ? formatBytes(memoryUsage*1024*1024): "- MB",',
    '  }',
    '  return (',
    '    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">',
    '      {STATS.map(s => {',
    '        const Icon = s.icon',
    '        return (',
    '          <div key={s.id} className={cn("bg-slate-900 rounded-xl border p-5 flex items-start space-x-4 transition-all", s.border, isProcessing && "shadow-lg")}>',
    '            <div className={cn("p-2.5 rounded-lg flex-shrink-0", s.bg)}><Icon className={cn("h-5 w-5", s.color)} /></div>',
    '            <div className="min-w-0 flex-1">',
    '              <p className="text-xs text-slate-500 font-medium uppercase tracking-wider truncate">{s.title}</p>',
    '              <p className={cn("text-2xl font-bold mt-1 font-mono", s.color)}>{vals[s.id]}</p>',
    '            </div>',
    '          </div>',
    '        )',
    '      })}',
    '    </div>',
    '  )',
    '}',
]))

w("components/video/video-player.tsx", '\n'.join([
    '"use client"',
    'import { useRef, useEffect } from "react"',
    'import { Button } from "@/components/ui/button"',
    'import { Play, Pause } from "lucide-react"',
    'import { cn } from "@/lib/utils"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'interface VideoPlayerProps { isPlaying: boolean; onPlayPause: () => void }',
    'export function VideoPlayer({ isPlaying, onPlayPause }: VideoPlayerProps) {',
    '  const videoRef = useRef<HTMLVideoElement>(null)',
    '  const canvasRef = useRef<HTMLCanvasElement>(null)',
    '  const { showPose, showBoundingBoxes, showDepth } = useSystemStore()',
    '  useEffect(() => {',
    '    if (isPlaying && videoRef.current) { videoRef.current.src = "/api/video-stream"; videoRef.current.play().catch(console.error) }',
    '    else if (videoRef.current) { videoRef.current.pause() }',
    '  }, [isPlaying])',
    '  return (',
    '    <div className="bg-slate-900 rounded-xl border border-slate-800 overflow-hidden">',
    '      <div className="relative aspect-video bg-black">',
    '        <video ref={videoRef} className="w-full h-full object-contain" muted loop />',
    '        <canvas ref={canvasRef} className="absolute inset-0 w-full h-full pointer-events-none" width={1280} height={720} />',
    '        <div className="absolute top-3 left-3 flex gap-2">',
    '          {showPose          && <span className="text-xs bg-signverse-primary/80 text-white px-2 py-0.5 rounded-md backdrop-blur-sm">Pose</span>}',
    '          {showBoundingBoxes && <span className="text-xs bg-signverse-accent/80  text-white px-2 py-0.5 rounded-md backdrop-blur-sm">BBox</span>}',
    '          {showDepth         && <span className="text-xs bg-violet-500/80 text-white px-2 py-0.5 rounded-md backdrop-blur-sm">Depth</span>}',
    '        </div>',
    '        {!isPlaying && (',
    '          <div className="absolute inset-0 flex items-center justify-center bg-black/60 backdrop-blur-sm">',
    '            <div className="text-center space-y-4">',
    '              <Button size="lg" className="rounded-full w-20 h-20 bg-signverse-primary hover:bg-signverse-primary/90 shadow-2xl shadow-signverse-primary/40" onClick={onPlayPause}>',
    '                <Play className="h-8 w-8 ml-1" />',
    '              </Button>',
    '              <p className="text-slate-400 text-sm">Click to start the perception pipeline</p>',
    '            </div>',
    '          </div>',
    '        )}',
    '        {isPlaying && (',
    '          <div className="absolute top-3 right-3 flex items-center space-x-1.5 bg-black/60 backdrop-blur-sm px-3 py-1.5 rounded-full border border-signverse-alert/30">',
    '            <span className="w-2 h-2 rounded-full bg-signverse-alert animate-pulse" />',
    '            <span className="text-xs text-white font-semibold tracking-wider">LIVE</span>',
    '          </div>',
    '        )}',
    '      </div>',
    '      <div className="p-4 bg-slate-800/40 border-t border-slate-700/50">',
    '        <div className="flex items-center justify-between">',
    '          <Button variant={isPlaying ? "destructive" : "signverse"} onClick={onPlayPause} size="sm">',
    '            {isPlaying ? <><Pause className="h-4 w-4 mr-2"/>Stop Pipeline</> : <><Play className="h-4 w-4 mr-2"/>Start Pipeline</>}',
    '          </Button>',
    '          <div className="flex items-center space-x-2 text-sm text-slate-400">',
    '            <span className={cn("w-2 h-2 rounded-full transition-colors", isPlaying ? "bg-signverse-accent animate-pulse" : "bg-slate-600")} />',
    '            <span>{isPlaying ? "Processing" : "Idle"}</span>',
    '          </div>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  )',
    '}',
]))

w("components/control/control-panel.tsx", '\n'.join([
    '"use client"',
    'import { Switch } from "@/components/ui/switch"',
    'import { Label } from "@/components/ui/label"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'import { formatFPS, formatMilliseconds, formatBytes } from "@/lib/utils"',
    'interface ControlPanelProps { isPlaying: boolean; onPlayPause: () => void }',
    'export function ControlPanel({ isPlaying }: ControlPanelProps) {',
    '  const { showPose, showBoundingBoxes, showDepth, showInteractions,',
    '          setShowPose, setShowBoundingBoxes, setShowDepth, setShowInteractions,',
    '          fps, latency, memoryUsage } = useSystemStore()',
    '  const toggles = [',
    '    {id:"pose-toggle",        label:"Show Pose",      checked:showPose,          onChange:setShowPose},',
    '    {id:"bbox-toggle",        label:"Bounding Boxes", checked:showBoundingBoxes, onChange:setShowBoundingBoxes},',
    '    {id:"depth-toggle",       label:"Depth Map",      checked:showDepth,         onChange:setShowDepth},',
    '    {id:"interaction-toggle", label:"Interactions",   checked:showInteractions,  onChange:setShowInteractions},',
    '  ]',
    '  return (',
    '    <div className="bg-slate-900 rounded-xl border border-slate-800 p-6 space-y-6 h-full">',
    '      <h3 className="text-base font-semibold text-white">Perception Controls</h3>',
    '      <div className="space-y-4">',
    '        {toggles.map(({id, label, checked, onChange}) => (',
    '          <div key={id} className="flex items-center justify-between">',
    '            <Label htmlFor={id} className="text-sm text-slate-300 cursor-pointer">{label}</Label>',
    '            <Switch id={id} checked={checked} onCheckedChange={onChange} />',
    '          </div>',
    '        ))}',
    '      </div>',
    '      <div className="pt-4 border-t border-slate-800">',
    '        <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3">Performance</h4>',
    '        <div className="space-y-2.5 text-sm">',
    '          <div className="flex justify-between"><span className="text-slate-500">FPS</span><span className="font-mono text-slate-200">{isPlaying ? formatFPS(fps) : "-"}</span></div>',
    '          <div className="flex justify-between"><span className="text-slate-500">Latency</span><span className="font-mono text-slate-200">{isPlaying ? formatMilliseconds(latency) : "-"}</span></div>',
    '          <div className="flex justify-between"><span className="text-slate-500">Memory</span><span className="font-mono text-slate-200">{isPlaying ? formatBytes(memoryUsage*1024*1024) : "-"}</span></div>',
    '        </div>',
    '      </div>',
    '      <div className="pt-4 border-t border-slate-800">',
    '        <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3">Actions</h4>',
    '        <div className="space-y-1">',
    '          <button className="w-full text-left py-2 px-3 rounded-lg text-sm text-slate-300 hover:bg-slate-800 transition-colors">Capture Frame</button>',
    '          <button className="w-full text-left py-2 px-3 rounded-lg text-sm text-slate-300 hover:bg-slate-800 transition-colors">Export Data</button>',
    '          <button className="w-full text-left py-2 px-3 rounded-lg text-sm text-signverse-alert hover:bg-red-950/50 transition-colors font-medium">Emergency Stop</button>',
    '        </div>',
    '      </div>',
    '    </div>',
    '  )',
    '}',
]))

w("app/monitoring/page.tsx", '\n'.join([
    '"use client"',
    'import { useState } from "react"',
    'import { VideoPlayer } from "@/components/video/video-player"',
    'import { ControlPanel } from "@/components/control/control-panel"',
    'import { StatsGrid } from "@/components/stats/stats-grid"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'export default function MonitoringPage() {',
    '  const [isPlaying, setIsPlaying] = useState(false)',
    '  const { startPipeline, stopPipeline, isProcessing } = useSystemStore()',
    '  const handleStartStop = () => {',
    '    if (isProcessing) { stopPipeline(); setIsPlaying(false) }',
    '    else { startPipeline(); setIsPlaying(true) }',
    '  }',
    '  return (',
    '    <div className="space-y-6">',
    '      <div>',
    '        <h1 className="text-3xl font-bold text-white tracking-tight">Real-Time Monitoring</h1>',
    '        <p className="text-slate-400 mt-1.5 text-sm">Live perception system monitoring and control</p>',
    '      </div>',
    '      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">',
    '        <div className="lg:col-span-3"><VideoPlayer isPlaying={isPlaying} onPlayPause={handleStartStop} /></div>',
    '        <div className="lg:col-span-1"><ControlPanel isPlaying={isPlaying} onPlayPause={handleStartStop} /></div>',
    '      </div>',
    '      <StatsGrid />',
    '    </div>',
    '  )',
    '}',
]))

w("app/page.tsx", '\n'.join([
    '"use client"',
    'import Link from "next/link"',
    'import { Activity, Video, Users, Zap, ArrowRight, Database, Bot } from "lucide-react"',
    'import { Button } from "@/components/ui/button"',
    'import { useSystemStore } from "@/store/use-system-store"',
    'import { cn } from "@/lib/utils"',
    'const FEATURES = [',
    '  {icon:Video,   title:"Real-Time Monitoring",href:"/monitoring", description:"Live video stream with pose estimation and object detection overlays.",  color:"text-signverse-primary",bg:"bg-signverse-primary/10",border:"border-signverse-primary/20"},',
    '  {icon:Users,   title:"Multi-Person Tracking",href:"/tracking",  description:"ByteTrack-powered persistent identity tracking across frames.",          color:"text-signverse-accent", bg:"bg-signverse-accent/10", border:"border-signverse-accent/20"},',
    '  {icon:Activity,title:"Pose Analysis",        href:"/pose",      description:"Skeletal keypoint analysis and sign language gesture recognition.",       color:"text-violet-400",       bg:"bg-violet-400/10",       border:"border-violet-400/20"},',
    '  {icon:Database,title:"Dataset Management",   href:"/datasets",  description:"Manage and export perception datasets for model training.",              color:"text-amber-400",        bg:"bg-amber-400/10",        border:"border-amber-400/20"},',
    '  {icon:Bot,     title:"Model Registry",       href:"/models",    description:"Version-controlled model registry with performance benchmarks.",         color:"text-sky-400",          bg:"bg-sky-400/10",          border:"border-sky-400/20"},',
    '  {icon:Zap,     title:"Pipeline Control",     href:"/monitoring",description:"Orchestrate and configure the full AI perception pipeline.",             color:"text-pink-400",         bg:"bg-pink-400/10",         border:"border-pink-400/20"},',
    ']',
    'export default function DashboardPage() {',
    '  const { isProcessing, fps, detectedPersons } = useSystemStore()',
    '  return (',
    '    <div className="space-y-8">',
    '      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-slate-900 via-slate-900 to-signverse-dark border border-slate-800 p-8">',
    '        <div className="absolute inset-0 bg-gradient-to-br from-signverse-primary/5 to-transparent pointer-events-none" />',
    '        <div className="relative">',
    '          <div className="flex items-center space-x-2 mb-4">',
    '            <div className={cn("w-2 h-2 rounded-full", isProcessing ? "bg-signverse-accent animate-pulse" : "bg-slate-600")} />',
    '            <span className="text-xs font-semibold text-slate-400 uppercase tracking-wider">{isProcessing ? "Pipeline Active" : "Pipeline Idle"}</span>',
    '          </div>',
    '          <h1 className="text-4xl font-bold text-white tracking-tight">SignVerse AI<br /><span className="text-signverse-primary">Perception System</span></h1>',
    '          <p className="text-slate-400 mt-3 max-w-xl text-sm leading-relaxed">Professional-grade real-time monitoring for sign language perception. Powered by YOLOv8, MediaPipe, and ByteTrack.</p>',
    '          <div className="flex items-center space-x-4 mt-6">',
    '            <Link href="/monitoring"><Button variant="signverse" size="lg" className="gap-2">Open Monitor <ArrowRight className="h-4 w-4"/></Button></Link>',
    '            {isProcessing && <div className="text-sm text-slate-400 font-mono bg-slate-800 px-3 py-2 rounded-lg">{fps.toFixed(1)} FPS</div>}',
    '          </div>',
    '        </div>',
    '      </div>',
    '      <div>',
    '        <h2 className="text-lg font-semibold text-white mb-4">Modules</h2>',
    '        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">',
    '          {FEATURES.map(f => (',
    '            <Link key={f.title} href={f.href} className="group">',
    '              <div className={cn("bg-slate-900 rounded-xl border p-5 transition-all duration-300 h-full hover:shadow-lg hover:-translate-y-0.5", f.border)}>',
    '                <div className={cn("w-10 h-10 rounded-lg flex items-center justify-center mb-4", f.bg)}><f.icon className={cn("h-5 w-5", f.color)} /></div>',
    '                <h3 className="text-white font-semibold mb-1 group-hover:text-slate-100">{f.title}</h3>',
    '                <p className="text-slate-500 text-sm leading-relaxed">{f.description}</p>',
    '              </div>',
    '            </Link>',
    '          ))}',
    '        </div>',
    '      </div>',
    '    </div>',
    '  )',
    '}',
]))

w("next.config.js", '\n'.join([
    '/** @type {import("next").NextConfig} */',
    'const nextConfig = {',
    '  reactStrictMode: true,',
    '  async rewrites() { return [{ source: "/api/:path*", destination: "http://localhost:8000/:path*" }] },',
    '}',
    'module.exports = nextConfig',
]))

w("postcss.config.js", 'module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } }')

w("tsconfig.json", '\n'.join([
    '{',
    '  "compilerOptions": {',
    '    "target": "es5", "lib": ["dom","dom.iterable","esnext"],',
    '    "allowJs": true, "skipLibCheck": true, "strict": true, "noEmit": true,',
    '    "esModuleInterop": true, "module": "esnext", "moduleResolution": "bundler",',
    '    "resolveJsonModule": true, "isolatedModules": true, "jsx": "preserve", "incremental": true,',
    '    "plugins": [{"name":"next"}], "paths": {"@/*": ["./*"]}',
    '  },',
    '  "include": ["next-env.d.ts","**/*.ts","**/*.tsx",".next/types/**/*.ts"],',
    '  "exclude": ["node_modules"]',
    '}',
]))

print("\\nAll files written successfully.")
